// <auto-generated />
using System;
using Avant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Avant.Api.Migrations
{
    [DbContext(typeof(AvantDbContext))]
    [Migration("20251118034236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avant.Api.Models.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("GerenteId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("GerenteId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Avant.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PlanoCarreira")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EquipeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Avant.Api.Models.Equipe", b =>
                {
                    b.HasOne("Avant.Api.Models.Usuario", "Gerente")
                        .WithMany("EquipesGerenciadas")
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("Avant.Api.Models.Usuario", b =>
                {
                    b.HasOne("Avant.Api.Models.Equipe", "Equipe")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Avant.Api.Models.Equipe", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("Avant.Api.Models.Usuario", b =>
                {
                    b.Navigation("EquipesGerenciadas");
                });
#pragma warning restore 612, 618
        }
    }
}
